#ifndef REW_BUILTIN_COMPARE_HPP
#define REW_BUILTIN_COMPARE_HPP

#if __cplusplus > 201703L
#include <compare> // strong_ordering

#include <Rew/Reflectable.hpp>

REFLECTABLE_DECLARATION(std::partial_ordering)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE(std::partial_ordering)
REFLECTABLE_INIT()

REFLECTABLE_DECLARATION(std::weak_ordering)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE(std::weak_ordering)
REFLECTABLE_INIT()

REFLECTABLE_DECLARATION(std::strong_ordering)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE(std::strong_ordering)
REFLECTABLE_INIT()
#endif // if

#endif // REW_BUILTIN_COMPARE_HPP
