#ifndef EIGHTREFL_BUILTIN_COMPARE_HPP
#define EIGHTREFL_BUILTIN_COMPARE_HPP

#if __cplusplus > 201703L
#include <compare> // strong_ordering

#include <Eightrefl/Reflectable.hpp>

REFLECTABLE_DECLARATION(std::partial_ordering)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE_DECLARATION(std::weak_ordering)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE_DECLARATION(std::strong_ordering)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()
#endif // if

#endif // EIGHTREFL_BUILTIN_COMPARE_HPP
