#ifndef EIGHTREFL_BUILTIN_FLOATING_HPP
#define EIGHTREFL_BUILTIN_FLOATING_HPP

#include <Eightrefl/Reflectable.hpp>

#include <Eightrefl/BuiltIn/BuiltIn.hpp>

REFLECTABLE_DECLARATION(float)
    REFLECTABLE_REGISTRY(eightrefl::builtin())
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE_DECLARATION(double)
    REFLECTABLE_REGISTRY(eightrefl::builtin())
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE_DECLARATION(long double)
    REFLECTABLE_REGISTRY(eightrefl::builtin())
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

#endif // EIGHTREFL_BUILTIN_FLOATING_HPP
