#ifndef EIGHTREFL_BUILTIN_TYPE_INFO_HPP
#define EIGHTREFL_BUILTIN_TYPE_INFO_HPP

#include <typeinfo> // type_info

#include <Eightrefl/Reflectable.hpp>

REFLECTABLE_DECLARATION(std::type_info)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

#endif // EIGHTREFL_BUILTIN_TYPE_INFO_HPP
