#ifndef EIGHTREFL_BUILTIN_TYPE_INDEX_HPP
#define EIGHTREFL_BUILTIN_TYPE_INDEX_HPP

#include <typeindex> // type_index

#include <Eightrefl/Reflectable.hpp>

REFLECTABLE_DECLARATION(std::type_index)
    BUILTIN_REFLECTABLE()
REFLECTABLE_DECLARATION_INIT()

#endif // EIGHTREFL_BUILTIN_TYPE_INDEX_HPP
