#ifndef EIGHTREFL_DETAIL_MACRO_HPP
#define EIGHTREFL_DETAIL_MACRO_HPP

#define EIGHTREFL_DEPAREN(arg) EIGHTREFL_DEPAREN_IMPL(EIGHTREFL_UATE arg)
#define EIGHTREFL_UATE(...) EIGHTREFL_UATE __VA_ARGS__
#define EIGHTREFL_DEPAREN_IMPL(...) EIGHTREFL_DEPAREN_IMPL_(__VA_ARGS__)
#define EIGHTREFL_DEPAREN_IMPL_(...) EIGHTREFL_EVAL ## __VA_ARGS__
#define EIGHTREFL_EVALEIGHTREFL_UATE

#define EIGHTREFL_TO_STRING(...) EIGHTREFL_TO_STRING_IMPL(EIGHTREFL_DEPAREN(__VA_ARGS__))
#define EIGHTREFL_TO_STRING_IMPL(...) EIGHTREFL_TO_STRING_IMPL_(__VA_ARGS__)
#define EIGHTREFL_TO_STRING_IMPL_(...) #__VA_ARGS__

#endif // EIGHTREFL_DETAIL_MACRO_HPP
