#ifndef TEST_REFLECTION_SELF_TEST_META
#define TEST_REFLECTION_SELF_TEST_META

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::meta_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_META
