#ifndef TEST_REFLECTION_SELF_TEST_REGISTRY
#define TEST_REFLECTION_SELF_TEST_REGISTRY

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::registry_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_REGISTRY
