#ifndef TEST_REFLECTION_SELF_TEST_FUNCTION
#define TEST_REFLECTION_SELF_TEST_FUNCTION

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::function_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_FUNCTION
