#ifndef TEST_REFLECTION_SELF_TEST_INJECTION
#define TEST_REFLECTION_SELF_TEST_INJECTION

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::injectable_t)
REFLECTABLE_DECLARATION_INIT()

REFLECTABLE_DECLARATION(rew::injection_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_INJECTION
