#ifndef TEST_REFLECTION_SELF_TEST_REFLECTION
#define TEST_REFLECTION_SELF_TEST_REFLECTION

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::reflection_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_REFLECTION
