#ifndef TEST_REFLECTION_SELF_TEST_TYPE
#define TEST_REFLECTION_SELF_TEST_TYPE

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::type_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_TYPE
