#ifndef TEST_REFLECTION_SELF_TEST_PARENT
#define TEST_REFLECTION_SELF_TEST_PARENT

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::parent_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_PARENT
