#ifndef TEST_REFLECTION_SELF_TEST_PROPERTY
#define TEST_REFLECTION_SELF_TEST_PROPERTY

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::property_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_PROPERTY
