#ifndef TEST_REFLECTION_SELF_TEST_FACTORY
#define TEST_REFLECTION_SELF_TEST_FACTORY

#include <RewTestingBase.hpp>

REFLECTABLE_DECLARATION(rew::factory_t)
REFLECTABLE_DECLARATION_INIT()

#endif // TEST_REFLECTION_SELF_TEST_FACTORY
