#ifndef REW_DETAIL_MACRO_HPP
#define REW_DETAIL_MACRO_HPP

#define REW_DEPAREN(arg) REW_DEPAREN_IMPL(REW_UATE arg)
#define REW_UATE(...) REW_UATE __VA_ARGS__
#define REW_DEPAREN_IMPL(...) REW_DEPAREN_IMPL_(__VA_ARGS__)
#define REW_DEPAREN_IMPL_(...) REW_EVAL ## __VA_ARGS__
#define REW_EVALREW_UATE

#define REW_TO_STRING(...) REW_TO_STRING_IMPL(REW_DEPAREN(__VA_ARGS__))
#define REW_TO_STRING_IMPL(...) REW_TO_STRING_IMPL_(__VA_ARGS__)
#define REW_TO_STRING_IMPL_(...) #__VA_ARGS__

#endif // REW_DETAIL_MACRO_HPP
