name: Eightrefl-Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Eightrefl: ${{ github.workspace }}

    steps:
    - name: "Download project"
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: "Setup Ubuntu (Dev)"
      run: |
        cmake --version
        gcc --version
        g++ --version
        ldd --version

    - name: "Regenerate and Rebuild project"
      run: |
        cd ${Eightrefl}
        rm -rf Intermediate
        cmake -S . -B Intermediate -G Ninja \
          -DCMAKE_BUILD_TYPE=Debug \
          -DCMAKE_C_COMPILER=gcc \
          -DCMAKE_CXX_COMPILER=g++ \
          -DEIGHTREFL_FULLY_ENABLE=ON \
          -DEIGHTREFL_RTTI_ALL_ENABLE=ON \
          -DEIGHTREFL_DEV_ENABLE=OFF \
          -DEIGHTREFL_BUILD_TEST_LIBS=ON
        cmake --build Intermediate --parallel

    - name: "Package and Upload project"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}
        path: |
          ${{ env.Eightrefl }}/Binaries

    - name: "Test project"
      run: |
        cd "${Eightrefl}/Binaries"
        ./Launcher