name: Eightrefl-Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      Eightrefl: ${{ github.workspace }}

    steps:
    - name: "Download project"
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: "Setup Windows (Dev)"
      run: |
        cmake --version
        clang --version
        clang++ --version

    - name: "Regenerate and Rebuild project"
      shell: cmd
      run: |
        cd %Eightrefl%
        rmdir /s /q Intermediate
        cmake -S . -B Intermediate -G Ninja ^
          -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ^
          -DEIGHTREFL_FULLY_ENABLE=ON ^
          -DEIGHTREFL_RTTI_ALL_ENABLE=ON ^
          -DEIGHTREFL_DEV_ENABLE=ON ^
          -DEIGHTREFL_BUILD_TEST_LIBS=ON
        cmake --build Intermediate --parallel

    - name: "Package and Upload project"
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.workflow }}
        path: |
          ${{ env.Eightrefl }}/Binaries

    - name: "Test project"
      shell: cmd
      run: |
        cd "%Eightrefl%/Binaries"
        Launcher.exe